# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98a1c86d73d5f22c2d221e00acb081a74153817fbed1ae56e083a8b479129978403d69e0f1a5b36799ec6f05be7bc459f69a5cde86ff1633bf4682fc8997ebb

test:
  secret_key_base: 561716cc847b9e91c7f8a44413159ec1e7fd15cba8d62c86eecdbb1f8cff12fc229cfd5599e10627d3a2713097dc5048698afe54aba8f9de31075d88e538a06c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
